# Называем workflow
name: pw test

# Когда запускать тесты
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

# Сама джоба
jobs:
  # Название джобы
  test:
    timeout-minutes: 60
    # задаем окружение
    runs-on: ubuntu-latest
    
    steps:
    # делаем чекаут
    - uses: actions/checkout@v4
    
    # устанавливаем ноду
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    # устанавливаем зависимости
    - name: Install dependencies
      run: npm ci
    
    # устанавливаем PW
    - name: Install Playwright
      run: npx playwright install --with-deps
    
    # запускаем тесты
    - name: Run Playwright tests
      run: npm run test
